config/routes.rb
Rails.application.routes.draw do
  root "galleries#index"
  resources :galleries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: true, length: { is: 5 }
  has_many :paintings
  STATES = [["ALABAMA", "AL"],
  ["Alaska", "AK"],
  ["Massachusetts", "MA"],
  ["Illinois", "IL"]]
end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :gallery
  validates :title, presence: true
  validates :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
    @state_collection = Gallery::STATES
  end



  def create
    @gallery = Gallery.new(params_strong)
    if @gallery.save
      flash[:notice] = "You saved a dope gallery"
      redirect_to galleries_path
    else
      flash[:notice] = @gallery.errors.full_messages.to_sentence
      @state_collection = Gallery::STATES
      render :new
    end
  end



  private
  def params_strong
    params.require(:gallery).permit(
      :name,
      :city,
      :state,
      :zip,
      :description
    )
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @gallery = Gallery.find(params[:gallery_id])
    @paintings = @gallery.paintings
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new
  end



  def create
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new(params_strong)
    @painting.gallery = @gallery
    if @painting.save
      flash[:notice] = "You saved a dope painting"
      redirect_to paintings_path
    else
      flash[:notice] = @painting.errors.full_messages.to_sentence

      render :new
    end
  end



  private
  def params_strong
    params.require(:painting).permit(
      :title,
      :artist
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_form.html.erb
<%= form_for (@gallery) do |f| %>
<% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :city%>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state%>
    <%= f.select :state, options_for_select(@state_collection) %>
  </div>

  <div>
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.submit(value="Submit the cool form for a new rad art gallery") %>
  </div>

<% end %>

app/views/galleries/index.html.erb
<h1>Galleries</h1>

<ul>
  <% @galleries.each do |gallery| %>
    <li><%= link_to gallery.name, gallery %> </li>
  <% end %>
</ul>

<%= link_to "New Gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<h1> New Gallery </h1>
<%= render 'form' %>

<%= link_to 'cancel', galleries_path %>

app/views/galleries/show.html.erb
<h1> <%= @gallery.name %> </h1>

  <ul>
    <li>City: <%= @gallery.city %></li>
    <li>State: <%= @gallery.state %></li>
    <li>Zip: <%= @gallery.zip %></li>
    <% unless @gallery.description.nil? %>
      <li>Description: <%= @gallery.description %></li>
    <% end %>
  </ul>

<%= link_to "back", galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gallery Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>